config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   root to: "pages#index"
   

   devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :items do
resources :itemcomments
end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :user
	 has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/itemcomment.rb
class Itemcomment < ApplicationRecord
belongs_to :user
	belongs_to :item

validates :text, presence: true
validates :text, length: { in: 1..400}
validates :text, format: { with: /[a-zA-Z_#][\w.!?,&|@#$%^:;'"-]*/ }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :titles
         has_many :itemcomments


         has_attached_file :avatar, styles: { medium: "300x300>", small: "50x50>" }, default_url: "/images/thumb/default.png"
         validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

         validates :nickname, :password, :email, presence: true 
         validates :nickname, length: { in: 6..15 }
         validates :nickname, :email, uniqueness: true
         validates :nickname, format: { with: /\A[a-zA-Z0-9]+\Z/ }
         validates :nickname, format: { without: /\s/ }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :devise_sign_up_params, if: :devise_controller?
  protect_from_forgery with: :exception

  private

  def devise_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys:[:attribute, :nickname, :avatar])
  end

end

app/controllers/itemcomments_controller.rb
class ItemcommentsController < ApplicationController
	before_action :authenticate_user!
    
def create
	params[:itemcomment][:item_id] = params[:item_id]
	params[:itemcomment][:user_id] = current_user.id
	@comment = Itemcomment.create(itemcomments_params)
    if @comment.save
	   redirect_to item_path(params[:item_id])
    else
    	@comment.errors.full_messages.each do |msg|
        @msg = msg
    end
    flash[:notice] = "#{@msg}"
    redirect_to item_path(params[:item_id])
end
end


private

def itemcomments_params
    params.require(:itemcomment).permit(:user_id, :item_id, :text)
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	  before_action :authenticate_user!, exist:[:show]
	  before_action :set_item,only:[:edit,:update,:destroy,:show]

	  def new
	  	@item=Item.new
	  end

	  def create
	  	pp params[:item][:user_id]=current_user.id
	  	params[:item][:image]
	  	pp @item=Item.create(item_params)
	  	if @item.save
	  		redirect_to root_path
	  	else
	  	render 'new'
	  end
	  end

	  def edit
	  	
	  end

	  def update
	  	@item.update(item_params)
	    redirect_to root_path
	  end

	  def destroy
     @item.destroy
   redirect_to root_path
	  end

	  def show
	  	@comments=Itemcomment.where(item_id: @item.id)
	  end

	  private

	  def item_params
	  	params.require(:item).permit(:name,:description,:user_id,:category_id,:image)
	  end

	  def set_item
	  	@item=Item.find(params[:id])
	  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@items=Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/itemcomments_helper.rb
module ItemcommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/items/_form.html.erb
<p><%= f.label :name %></p>
<%= f.text_field :name %><br />

<p><%= f.label :description %></p>
<%= f.text_area :description %><br />

<p><%= f.label "Добавить фото" %></p>
<%= f.file_field :image %></br>

<p><%= f.submit "Сохранить"%></p></br>

app/views/items/edit.html.erb
<%= form_for :item, url:item_path, method: :patch do |f| %>
<% if @item.errors.any? %>
<% @item.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
<% end %>

<%= render 'items/form', f:f %>

<% end %>
<% form_for @item, url:item_path do |f|%>
<%=render 'items/form', f:f %>
<%end%>

app/views/items/new.html.erb
<%= form_for @item, url:items_path do |f|%>
<%=render 'items/form', f:f %>
<%end%>

app/views/items/show.html.erb
<center><h1><%= @item.name%></h1>
<p><%= @item.description%></p>

<% @comments.each do |comment| %>
<%= comment.text %> 
<hr>
<% end %>
<%= form_for :itemcomment, url: item_itemcomments_path(item_id: @item.id) do |f| %>
<% if flash[:notice] %>
        <%= flash[:notice]%>
<% end %>

<p><%= f.label "Введите комментарий" %></p>
<p><%= f.text_area :text, cols: 20, rows: 5 %></p><br/>

<p><%= f.submit "Отправить"%></p></br>

<%end%>
</center>

app/views/layouts/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <div class="footer">
      <div class="container">
              <h3>OLX</h3>
              <a href='https://facebook.com'><i class="fa fa-facebook fa-3x fa-fw"></i></a>
              <a href='https://twitter.com'><i class="fa fa-twitter fa-3x fa-fw"></i></a>
              <a href='https://www.youtube.com'><i class="fa fa-youtube-play fa-3x fa-fw"></i></a>

     </span>

      </div>

    </div>

app/views/layouts/_navbar.html.erb
<style>
.container-fluid a{
  text-decoration:none;
  color: grey;
}
</style>
<div class="container">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header"></div>

    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "OLX", root_path, class: "navbar-brand"%></li>

      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li>
    </ul>


    <form class="navbar-form navbar-left" action="/action_page.php">
  <div class="input-group">
    <input type="text" class="form-control" placeholder="Search">
    <div class="input-group-btn">
      <button class="btn btn-default" type="submit">
        <i class="glyphicon glyphicon-search"></i>
      </button>
    </div>
  </div>
</form> 



    <ul class="nav navbar-nav navbar-right">
    <% if current_user.nil? %>
    <li>
    <%= link_to new_user_registration_path do %>
      <i class="glyphicon glyphicon-user"></i> Sing up
      <%end%>
      </li>
        <li>
    <%= link_to user_session_path do %>
      <i class="glyphicon glyphicon-log-in"></i> Login
      <%end%>
        </li>

      <% else %> 
      <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="glyphicon glyphicon-log-in"></i> Logout
  <%end%>
      </li>
       <% end %>
    </ul>


  
  </div>
  </div>
  </div>
 
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sayt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
    <div>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/index.html.erb
<style>
.con a{
  text-decoration:none;
 }
</style>


<div class="con">
<div class="container">
<div class="row">
<center><%= link_to "Добавить новое объявление", new_item_path, class: "btn btn-primary active btn-block btn-lg" %></center>

<% @items.each do |item| %></center></br>
  
    <div class="thumbnail">
      
       <center> </br><p><%= image_tag(item.image.url, width: 300, height: 300)%></p>

  <h1><%= link_to item.name, item_path(item.id) %></h1>

  
  <%= image_tag item.user.avatar.url(:thumb), width: 30, height: 30 %>

  <p><span style="color: green;">Автор:<%= item.user.nickname %></span>


  <span style="color: grey;">| Опубликовано: <%= item.created_at %></span></p>

  <% if current_user != nil and current_user.id == item.user_id %>

    <p><span style="color: #38678b;">

  <%= link_to "Редактировать",  edit_item_path(item.id), class: "btn btn-primary active" %>

  <%= link_to "Удалить", item_path(item.id), class: "btn btn-primary active", data: {confirm: 'Are you sure?'}, method: :delete %>
 </span></p>
       </center>
      >
   
  <%end%>
</div>

<%end%> 

</div>
    </div>
     </div
 
 

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>